---
kind: pipeline
type: docker
name: Test

steps:
  - name: validate frontend
    image: eryalus/jhipster-ci:v0.1.amd64
    commands:
      - npm install
      - npm test
  - name: validate build
    image: eryalus/jhipster-ci:v0.1.amd64
    commands:
      - ls
      - ./mvnw clean verify
