---
kind: pipeline
type: docker
name: Main pipeline

steps:
  - name: Validate frontend
    image: eryalus/jhipster-ci:v0.1.amd64
    commands:
      - npm install
      - npm test
  - name: Validate build
    image: eryalus/jhipster-ci:v0.1.amd64
    commands:
      - ./mvnw clean verify
  - name: Deploy - PRO
    image: eryalus/ansible:latest
    environment:
      host:
        from_secret: host
      host_user:
        from_secret: host_user
      ssh_key:
        from_secret: ssh_key
    commands:
      - echo "[webservers]" > hosts
      - echo $host >> hosts
      - echo "[defaults]" > ansible.cfg
      - echo "host_key_checking = False" >> ansible.cfg
      - mkdir /root/.ssh
      - echo "$ssh_key" > /root/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa
      - ansible-playbook ansible-deploy.yaml -i hosts
    when:
      event: ["promote"]
      target: ["pro"]
