name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    working-directory: webapp
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: Test build
      run: npm run build
