name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test webapp (lint & build)
    env:
      working-directory: webapp
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: Test build
      run: npm run build
